config/routes.rb
Rails.application.routes.draw do
  root 'students#index'
  #get 'teachers/list_paper', to:'teachers#list_paper'
   resources :students 
   resources :teachers do
     resources :questions
   end
   resources :admins do
    resources :questions
   end
   resources :questionpapers
   resources :answers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_many :questions, as: :questionable
    # accepts_nested_attributes_for :questions
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
   belongs_to :question_paper
   belongs_to :questionable, polymorphic: true
   has_many :answer
   validates :title, :option1,:option2, :option3,:option4, presence: true
end

app/models/question_paper.rb
class QuestionPaper < ApplicationRecord
   has_many :questions
   belongs_to :teacher
   has_many :students
   validates :name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :question_paper, optional: true
    has_many :question 
    after_create :assign_question_paper
    validates :name, presence: true
    
    private
    def assign_question_paper
        @question = QuestionPaper.all.sample
        self.update(question_paper_id: @question.id)
    end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
   has_many :questions, as: :questionable
   has_many :question_papers
   validates :name, presence: true

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
    # @admin.questions.build
  end

  def show
    @admin = Admin.find(params[:id])
  end

  private

  def admin_params
    params.require(:admin).permit(:name)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
    @teacher = Teacher.find(params[:teacher_id])
  end

  def new
    @student = Student.find(params[:student_id])
    @answer = Answer.new
  end

  def create      
    questions = params[:answer][:questions]
    questions.each do |key, value|
       @answer = Answer.create(
       student_id: params[:answer][:student_id],
       question_id: value [:question_id],
       answer: value[:answer]
      )
    end
    if @answer.save
      redirect_to root_path
    else
      render:new
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionpapers_controller.rb
class QuestionpapersController < ApplicationController
  def index
    @questionpapers = QuestionPaper.all
  end

  def new
    @teacher = Teacher.find(params[:teacher_id])
    @questionpaper = QuestionPaper.new
  end

  def create
    @questionpaper = QuestionPaper.create(question_paper_params)
    if @questionpaper.save
      redirect_to teachers_path
    else
      render :new
    end
  end

  private

  def question_paper_params
    params.require(:question_paper).permit(:name, :teacher_id)
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   before_action :set_type_id
    
  def index
    @questions = @questionable.questions
  end

  def new
    # @teacher = Teacher.find(params[:teacher_id])
    @question = @questionable.questions.new
  end

  def create
    @question = @questionable.questions.create!(question_params)
    if @question.save
      redirect_to students_path
    else
      render :new
    end
  end

  private
  
  def question_params
    params.require(:question).permit(:title, :option1, :option2, :option3, :option4, :question_paper_id)
  end

  def set_type_id
    resource, id = request.path.split('/')[1, 2]
    @questionable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    if @student.save
       redirect_to root_path
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  private

  def student_params
    params.require(:student).permit(:name,:question_paper_id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<br>
<div>
<% @admins.each do |admin| %>
<strong style="padding:30px">Name: <%= admin.name %></strong>
<%= link_to "Create Question",new_admin_question_path(admin) %>
<%= link_to "Overview", admin_path(admin),style: 'padding:30px' %>
<% end %>
</div>

app/views/admins/show.html.erb
<br>
<div class="container"><% @admin.questions.each do |que| %>
<div class="card">
  <div class="card-header" style="background-color:#0B0A0A; color:white">
    <%= que.id %>. <%= que.title %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item" style="padding-left:40px">A. <%= que.option1 %></li>
    <li class="list-group-item" style="padding-left:40px">b. <%= que.option2 %></li>
    <li class="list-group-item" style="padding-left:40px">c. <%= que.option3 %></li>
    <li class="list-group-item" style="padding-left:40px">d. <%= que.option4 %></li>
  </ul>
</div>
<br>
<% end %>
</div>

app/views/answers/_form.html.erb
<br>
<div class="container">
<center><h3>Answer the Questions </h3></center>
<br>
<%= form_with(model:@answer) do |f| %> 
   
  <%= f.hidden_field :student_id, value: @student.id %>
  <% @student.question_paper.questions.each_with_index do |q,index| %>
    <strong><%= q.id %>.<%= q.title %></strong>
    <div class="form-check">
    
     <%= f.hidden_field "questions[#{index}][question_id]", value: q.id %>
     <%= f.radio_button "questions[#{index}][answer]", q.option1, class:"form-check-input" %><%= q.option1 %> <br>  
     <%= f.radio_button "questions[#{index}][answer]", q.option2, class:"form-check-input" %><%= q.option2 %> <br> 
     <%= f.radio_button "questions[#{index}][answer]", q.option3, class:"form-check-input" %><%= q.option3 %> <br> 
     <%= f.radio_button "questions[#{index}][answer]", q.option4, class:"form-check-input" %><%= q.option4 %> <br> 
    </div>
   <br>
  <% end %> 
  <div>
    <%= f.submit :submit,class:'btn btn-dark' %>
  </div>
  <br>
<% end %>
</div>










  <%#= f.hidden_field :question_id, value: @student.question_paper.questions.ids %>
 <%# <% @student.question_paper.questions.each do || %> 
 <%# <% @student_questionpaper_id.id.questions.each do |q| %> 
  <%#= @student_questionpaper_id.id.questions.find(23).title %>
  <%# <%= @student_questionpaper.inspect %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/index.html.erb
<div class="container">
  <% @teacher.question_papers.each do |qp| %>
  <div class="answerDisplay">
    <strong>QuestionPaper:</strong><span><%= qp.name rescue "" %></span><br>
     <% qp.questions.each do |q| %> 
       <%= q.id %>.<strong>Question:</strong><span><%= q.title %></span><br>
        <% q.answer.each do |a| %>
          <strong>Submited Students:</strong>
          <span><%= a.student.name.capitalize %></span>
          <div>
          <strong><%= a.student.name.capitalize %> Answer:</strong>
          <span><%= a.answer %></span>
          </div>
        <% end %>
        <br>
     <% end %>
  </div>
  <% end %>
</div>
<br>

app/views/answers/new.html.erb
<%= render 'form' %>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<br><nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Student",root_path,class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
             <%= link_to "Teacher",teachers_path,class: 'nav-link active' %>
        </li>
        <li class="nav-item">
           <%= link_to "Admin",admins_path,class: 'nav-link active' %>

        </li>
       
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
  </head>
  <body>
  <div class="container">
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </div>
    
  </body>
</html>

app/views/questionpapers/_form.html.erb
<div class="container">
<br>
<%= form_with(model:@questionpaper, url: questionpapers_path(@questionpaper), method: :post,  id: 'questionpaperForm') do |f| %>
  <%= f.hidden_field :teacher_id, value: @teacher.id %>
  <div>
     <%= f.label :name,"Question Paper Title", class:'form-label' %> <%= f.text_field :name, class:'form-control' %>
  </div>
  <br /> 
    <%= f.submit :submit,class:'btn btn-dark' %>
  </div>
</div>
<% end %>

app/views/questionpapers/create.html.erb
<h1>Questionpapers#create</h1>
<p>Find me in app/views/questionpapers/create.html.erb</p>

app/views/questionpapers/index.html.erb
<h1>Questionpapers#index</h1>
<p>Find me in app/views/questionpapers/index.html.erb</p>

app/views/questionpapers/new.html.erb
<br>
<%= render 'form' %>

app/views/questions/_form.html.erb
<div class="container">
<center><h3>Create Question for Students </h3></center>
<br>
<%= form_for [@questionable,@question], html: {id: "question_form"} do |f| %>  
  <div>
     <%= f.label :question_paper_id,"Question Paper",class:'form-label' %><br>
     <%= f.select :question_paper_id,(QuestionPaper.all.map{|e| [e.name, e.id]}),class:'form-control',required: true %>
  </div>
  <br>
  <div>
     <%= f.label :title,"Title", class:'form-label' %> 
     <%= f.text_field :title, class:'form-control' %>
  </div>
  <br>
  <div>
     <%= f.label :option1,"Option1", class:'form-label' %> 
     <%= f.text_field :option1, class:'form-control' %>
  </div>
  <br>
   <div>
     <%= f.label :option2,"Option2", class:'form-label' %> 
     <%= f.text_field :option2, class:'form-control' %>
  </div>
  <br>
   <div>
     <%= f.label :option3,"Option3", class:'form-label' %> 
     <%= f.text_field :option3, class:'form-control' %>
  </div>
  <br>
   <div>
     <%= f.label :option4,"Option4", class:'form-label' %> 
     <%= f.text_field :option4, class:'form-control'%>
  </div>
  <br>
    <%= f.submit :submit,class:'btn btn-dark' %>
  </div>
  <br>
<% end %>
</div>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<br>
<%= render 'form' %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/index.html.erb
<br>
<%= link_to "Create Student",new_student_path %>
<% @students.each do |student| %>
<div class="card" style="margin-top:2px;">
  <div class="card-body">
    <h5 class="card-title"><%= student.name %></h5>
    <%= link_to "Show",student_path(student), class:"card-link" %>
    <%#= link_to "Summary",answers_path(student_id: student.id), class:"card-link" %>
  </div>
</div>
<% end %>

app/views/students/new.html.erb
<div class="container">
<br>
<%= form_with(model:@student, id: 'studentForm') do |f| %>
  <div class="studentname_input">
     <%= f.label :name,"Name", class:'form-label' %> 
     <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <div>
    <%= f.submit :submit,class:'btn btn-dark' %>
  </div>
  <br>
<% end %>
</div>
<%#= javascript_pack_tag 'formvalidation' %>

app/views/students/new.js.erb
$('#answer').show();

app/views/students/show.html.erb
<br>
<div class="container">
<strong>Name:</strong> <%= @student.name %><br>
<strong>Assigned paper:</strong> <%= @student.question_paper.name %><br><br>
<%= link_to "Back" ,root_path %>
<%= link_to "Start Quiz ", new_answer_path(student_id: @student.id) %>

</div>

app/views/teachers/index.html.erb
<br>
<div>
<% @teachers.each do |teacher| %>
<strong style="padding:30px">Name: <%= teacher.name %></strong>
<%= link_to "Create Question", new_teacher_question_path(teacher),style: 'padding:30px' %>
<%= link_to "Create Question Paper",new_questionpaper_path(teacher_id: teacher.id),style: 'padding:30px' %>
<%= link_to "Overview", teacher_path(teacher),style: 'padding:30px' %>
<%= link_to "Students Answers",answers_path(teacher_id: teacher.id) %>

<% end %>
</div>

app/views/teachers/list_paper.html.erb
<%# <% @teacher.question_papers.each do |tq| %>
   <%# Title: <%= tq.name %><br> 
<%# <% end %>

app/views/teachers/show.html.erb
<br>
<% @teacher.question_papers.each do |tp| %>
<strong> Paper Name: </strong> <%= tp.name%><br>
<% end %>
<br>
<div class="container"><% @teacher.questions.each do |que| %>
<div class="card">
  <div class="card-header" style="background-color:#0B0A0A; color:white">
    <%= que.id %>. <%= que.title %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item" style="padding-left:40px">A. <%= que.option1 %></li>
    <li class="list-group-item" style="padding-left:40px">b. <%= que.option2 %></li>
    <li class="list-group-item" style="padding-left:40px">c. <%= que.option3 %></li>
    <li class="list-group-item" style="padding-left:40px">d. <%= que.option4 %></li>
  </ul>
</div>
<br>
<% end %>
</div>